### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by stepgenn** [dufkan/pb173_project#18]
- [x] pridat MAC ke client-client komunikaci
- [x] PBKDF2 -> chceme to nejak vyuzit jako KDF u DR?
- [x] mame memory leaky?
- [x] vlastni DSA
- [x] podklady, proc nami pouzity generator nahodnych cisel je bezpecny
- [x] cpp check a clang na analyzu
- [x] prezentaci, 10-15 slajdu, ukazka, jak to funguje, bezpecnost...
